### ISSUE TITLE
Where is the code?

### ISSUE THREAD

**Issue by kangsik** [mishagray/SwiftTask#1]
I really want  to try your SwiftTask, but... where is the code?

**Comment by mishagray** [comment]
I never got this packaged up right.    I didn't even advertise this yet! 

Got something even better almost baked.  It's like Tasks but with type safety!

I basically converted BFTask into a typesafe Future/promise implantation. 

So you can specify the type of of value returned from the Task.  Simplifies the block handlers a lot.  

Requires ditching some objective-c interactivity.  But not totally.

**Comment by mishagray** [comment]
okay... SwiftTask is dead.  Future is FutureKit:
https://github.com/FutureKit/FutureKit
